name:                blas-test
version:             0.1.0.0
github:              "minoki/blas-test"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2021 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/blas-test#readme>

dependencies:
- base >= 4.7 && < 5
- blas-hs
# - blas-ffi
# - hblas: not buildable with base-4.14
- vector
- array

executables:
  blas-test-blashs:
    main:                Main.hs
    source-dirs:         blas-hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  blas-test-cuda:
    main:                Main.hs
    source-dirs:         cuda
    extra-libraries:     stdc++
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cuda
    - cublas
